#!/bin/bash

function start {
	mkdir -p ./tmp
	mkdir -p ./tmp/pids
	
	echo "Starting the scheduler processes..."
	RACK_ENV=$ENVIRONMENT bundle exec rake resque:scheduler 1>/dev/null 2>&1 &
	echo $! > ./tmp/pids/resque_sched.pid
	echo "Done"
}

function stop {
	echo "Stopping the rescue processes..."

	if [ -f ./tmp/pids/resque_sched.pid ]; then
		kill -9 `cat ./tmp/pids/resque_sched.pid`
		rm ./tmp/pids/resque_sched.pid
	fi

	echo "Done"
}

if [ $1 == 'start' ]; then
	ENVIRONMENT="local"
	if [ -n "$2" ]; then
		ENVIRONMENT=$2
	fi
		
	start
fi

if [ $1 == 'stop' ]; then
	ENVIRONMENT="local"
	if [ -n "$2" ]; then
		ENVIRONMENT=$2
	fi
	
	stop
fi

if [ $1 == 'restart' ]; then
	ENVIRONMENT="local"
	if [ -n "$2" ]; then
		ENVIRONMENT=$2
	fi
	
	stop
	start
fi