#!/bin/bash

function start {
	mkdir -p ./tmp
	mkdir -p ./tmp/pids
	
	echo "Starting the dashboard process..."
	RACK_ENV=$ENVIRONMENT rackup config.ru 1>/dev/null &
	echo $! > ./tmp/pids/dashboard.pid
	echo "Done"
}

function stop {
	echo "Stopping the dashboard processes..."

	if [ -f ./tmp/pids/dashboard.pid ]; then
		kill -9 `cat ./tmp/pids/dashboard.pid`
		rm ./tmp/pids/dashboard.pid
	fi

	echo "Done"
}

if [ $1 == 'start' ]; then
	ENVIRONMENT="local"
	if [ -n "$2" ]; then
		ENVIRONMENT=$2
	fi
	
	start
fi

if [ $1 == 'stop' ]; then
	ENVIRONMENT="local"
	if [ -n "$2" ]; then
		ENVIRONMENT=$2
	fi
	
	stop
fi

if [ $1 == 'restart' ]; then
	ENVIRONMENT="local"
	if [ -n "$2" ]; then
		ENVIRONMENT=$2
	fi
	
	stop
	start
fi